### PR TITLE
Added Slovak language support. Also added missing semicolons. Updatin…

### PR DESCRIPTION
**Pull request by jurajkapsz**
…g extension version to 2.3.3.

### CODE REVIEW

**Comment by jurajkapsz** [comment]
Should be done maybe in more commits, I made it as one. Just spank me if something. Thanks.

**Comment by nilshoerrmann** [comment]
Thanks!

**Comment by jurajkapsz** [comment]
Thanks very much Nils.

**Comment by nitriques** [comment]
Thanks both of you!

**Pull request merged**
